### For development purposes only ###
version: '3.6'
services:
  nginx:
    image: library/nginx:1
    container_name: cm-nginx
    ports:
      - 8443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/fullchain.pem:/etc/ssl/public.pem
      - ./ssl/privkey.pem:/etc/ssl/private.pem
    restart: on-failure

  credmgr:
    build:
      context: ./
      dockerfile: Dockerfile
    image: fabrictestbed/credmgr:0.7
    container_name: credmgr
    depends_on:
      - nginx
    volumes:
      - ./log/credmgr:/var/log/credmgr
      - ./config_template:/etc/credmgr/config
      - ./ssl/pubkey.pem:/etc/credmgr/public.pem
      - ./ssl/pubkey.pem:/etc/credmgr/cert.pem
      - ./ssl/privkey.pem:/etc/credmgr/private.pem
    #ports:
    #  - 7000:7000
    #  - 8100:8100
    restart: on-failure

  vouch-proxy:
    container_name: cm-vouch-proxy
    image: kthare10/vouch-proxy:refresh_token
    #ports:
    #  - 9090:9090
    volumes:
      - ./vouch:/config
      - ./data:/data
    restart: unless-stopped
