version: '3.6'

services:
    database:
        image: postgres:10
        container_name: database
        restart: always
        environment:
        - POSTGRES_PASSWORD=credmgr
        - POSTGRES_USER=credmgr
        - POSTGRES_DB=credmgr
        ports:
        - 5432:${POSTGRES_PORT:-5432}
    credmgr:
        container_name: credmgr
        hostname: credmgr
        image: credmgr:latest
        restart: always
        privileged: true
        cap_add:
            - SYS_ADMIN
        security_opt:
            - seccomp:unconfined
        tmpfs:
            - /run
            - /run/lock
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
            - ./log:/var/log
            - ./credentials:/var/lib/credmgr/credentials
            - "./docker/config:/etc/credmgr/config_docker"
            - "./docker/self.signed.crt:/etc/credmgr/hostcert.pem"
            - "./docker/self.signed.key:/etc/credmgr/hostkey.pem"
        ports:
        - "8082:8080"
        - "443:443"
