version: '3.6'

services:
    nginx:
        image: library/nginx:1
        container_name: nginx
        networks:
            - frontend
        ports:
            - 8443:443
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./ssl/fullchain.pem:/etc/ssl/public.pem
            - ./ssl/privkey.pem:/etc/ssl/private.pem
        restart: unless-stopped
    vouch-proxy:
        container_name: vouch-proxy
        image: kthare10/vouch-proxy:refresh_token
        volumes:
        - ./vouch:/config
        - ./data:/data
        restart: unless-stopped
    credmgr:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: credmgr
        hostname: credmgr
        image: credmgr:latest
        restart: on-failure
        depends_on:
            - nginx
            - vouch-proxy
        volumes:
            - ./log/credmgr:/var/log/credmgr
            - ./config_template:/etc/credmgr/config
            - ./ssl/pubkey.pem:/etc/credmgr/public.pem
            - ./ssl/privkey.pem:/etc/credmgr/private.pem
networks:
  frontend: