# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from fabric_cm.credmgr.swagger_server.models.base_model_ import Model
from fabric_cm.credmgr.swagger_server.models.status200_ok_paginated import Status200OkPaginated  # noqa: F401,E501
from fabric_cm.credmgr.swagger_server.models.token import Token  # noqa: F401,E501
from fabric_cm.credmgr.swagger_server import util


class Tokens(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, limit: int=None, offset: int=None, size: int=None, status: int=200, type: str=None, data: List[Token]=None):  # noqa: E501
        """Tokens - a model defined in Swagger

        :param limit: The limit of this Tokens.  # noqa: E501
        :type limit: int
        :param offset: The offset of this Tokens.  # noqa: E501
        :type offset: int
        :param size: The size of this Tokens.  # noqa: E501
        :type size: int
        :param status: The status of this Tokens.  # noqa: E501
        :type status: int
        :param type: The type of this Tokens.  # noqa: E501
        :type type: str
        :param data: The data of this Tokens.  # noqa: E501
        :type data: List[Token]
        """
        self.swagger_types = {
            'limit': int,
            'offset': int,
            'size': int,
            'status': int,
            'type': str,
            'data': List[Token]
        }

        self.attribute_map = {
            'limit': 'limit',
            'offset': 'offset',
            'size': 'size',
            'status': 'status',
            'type': 'type',
            'data': 'data'
        }
        self._limit = limit
        self._offset = offset
        self._size = size
        self._status = status
        self._type = type
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'Tokens':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The tokens of this Tokens.  # noqa: E501
        :rtype: Tokens
        """
        return util.deserialize_model(dikt, cls)

    @property
    def limit(self) -> int:
        """Gets the limit of this Tokens.


        :return: The limit of this Tokens.
        :rtype: int
        """
        return self._limit

    @limit.setter
    def limit(self, limit: int):
        """Sets the limit of this Tokens.


        :param limit: The limit of this Tokens.
        :type limit: int
        """

        self._limit = limit

    @property
    def offset(self) -> int:
        """Gets the offset of this Tokens.


        :return: The offset of this Tokens.
        :rtype: int
        """
        return self._offset

    @offset.setter
    def offset(self, offset: int):
        """Sets the offset of this Tokens.


        :param offset: The offset of this Tokens.
        :type offset: int
        """

        self._offset = offset

    @property
    def size(self) -> int:
        """Gets the size of this Tokens.


        :return: The size of this Tokens.
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size: int):
        """Sets the size of this Tokens.


        :param size: The size of this Tokens.
        :type size: int
        """

        self._size = size

    @property
    def status(self) -> int:
        """Gets the status of this Tokens.


        :return: The status of this Tokens.
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status: int):
        """Sets the status of this Tokens.


        :param status: The status of this Tokens.
        :type status: int
        """

        self._status = status

    @property
    def type(self) -> str:
        """Gets the type of this Tokens.


        :return: The type of this Tokens.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this Tokens.


        :param type: The type of this Tokens.
        :type type: str
        """

        self._type = type

    @property
    def data(self) -> List[Token]:
        """Gets the data of this Tokens.


        :return: The data of this Tokens.
        :rtype: List[Token]
        """
        return self._data

    @data.setter
    def data(self, data: List[Token]):
        """Sets the data of this Tokens.


        :param data: The data of this Tokens.
        :type data: List[Token]
        """

        self._data = data
