# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from fabric.credmgr.swagger_server.models.base_model_ import Model
from fabric.credmgr.swagger_server.models.success_value import SuccessValue  # noqa: F401,E501
from fabric.credmgr.swagger_server import util


class Success(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, status: int=None, message: str=None, value: SuccessValue=None, version: str=None):  # noqa: E501
        """Success - a model defined in Swagger

        :param status: The status of this Success.  # noqa: E501
        :type status: int
        :param message: The message of this Success.  # noqa: E501
        :type message: str
        :param value: The value of this Success.  # noqa: E501
        :type value: SuccessValue
        :param version: The version of this Success.  # noqa: E501
        :type version: str
        """
        self.swagger_types = {
            'status': int,
            'message': str,
            'value': SuccessValue,
            'version': str
        }

        self.attribute_map = {
            'status': 'status',
            'message': 'message',
            'value': 'value',
            'version': 'version'
        }
        self._status = status
        self._message = message
        self._value = value
        self._version = version

    @classmethod
    def from_dict(cls, dikt) -> 'Success':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The success of this Success.  # noqa: E501
        :rtype: Success
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> int:
        """Gets the status of this Success.

        status code  # noqa: E501

        :return: The status of this Success.
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status: int):
        """Sets the status of this Success.

        status code  # noqa: E501

        :param status: The status of this Success.
        :type status: int
        """

        self._status = status

    @property
    def message(self) -> str:
        """Gets the message of this Success.

        status message  # noqa: E501

        :return: The message of this Success.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this Success.

        status message  # noqa: E501

        :param message: The message of this Success.
        :type message: str
        """

        self._message = message

    @property
    def value(self) -> SuccessValue:
        """Gets the value of this Success.


        :return: The value of this Success.
        :rtype: SuccessValue
        """
        return self._value

    @value.setter
    def value(self, value: SuccessValue):
        """Sets the value of this Success.


        :param value: The value of this Success.
        :type value: SuccessValue
        """

        self._value = value

    @property
    def version(self) -> str:
        """Gets the version of this Success.

        Actor version  # noqa: E501

        :return: The version of this Success.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version: str):
        """Sets the version of this Success.

        Actor version  # noqa: E501

        :param version: The version of this Success.
        :type version: str
        """

        self._version = version
