# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from credmgr.swagger_server.models.base_model_ import Model
from credmgr.swagger_server import util


class CreateRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id_token: str=None):  # noqa: E501
        """CreateRequest - a model defined in Swagger

        :param id_token: The id_token of this CreateRequest.  # noqa: E501
        :type id_token: str
        """
        self.swagger_types = {
            'id_token': str
        }

        self.attribute_map = {
            'id_token': 'id_token'
        }
        self._id_token = id_token

    @classmethod
    def from_dict(cls, dikt) -> 'CreateRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The create_Request of this CreateRequest.  # noqa: E501
        :rtype: CreateRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id_token(self) -> str:
        """Gets the id_token of this CreateRequest.

        Identity Token  # noqa: E501

        :return: The id_token of this CreateRequest.
        :rtype: str
        """
        return self._id_token

    @id_token.setter
    def id_token(self, id_token: str):
        """Sets the id_token of this CreateRequest.

        Identity Token  # noqa: E501

        :param id_token: The id_token of this CreateRequest.
        :type id_token: str
        """
        if id_token is None:
            raise ValueError("Invalid value for `id_token`, must not be `None`")  # noqa: E501

        self._id_token = id_token
